### ISSUE TITLE
zotero import script not working in 0.7

### ISSUE THREAD

**Issue by Xunius** [papis/papis#97]
Hi,

I upgraded from 0.6 to 0.7 and tried the zotero import script following instructions from [here](https://papis.readthedocs.io/en/latest/search.html?q=bibtex&check_keywords=yes&area=default).

It's a brand new installation of papis, nothing in the library folder, no change made to the config file.
I ran

```
papis zotero /path/to/bib/file
```
I got
```
Traceback (most recent call last):
  File "/home/guangzhi/.config/papis/scripts/papis-zotero", line 72, in <module>
    add(entry, pdf_file)
  File "/home/guangzhi/.config/papis/scripts/papis-zotero", line 43, in add
    papis.commands.main(
AttributeError: module 'papis.commands' has no attribute 'main'
```

The same bib file imports fine in zotero. I tried the script a few days ago, but using 0.6. So could it be the 0.7 upgrade that breaks the script, can it be quickly fixed?

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

Possibly related issues are https://github.com/alejandrogallo/papis/issues/18 (Import bib (zotero) fails finding file), https://github.com/papis/papis/issues/58 (Papis tests don't work with bibtexparser 1.0.1), https://github.com/alejandrogallo/papis/issues/17 (Import bib (zotero) fails if field is missing), https://github.com/papis/papis/issues/87 (Scripts repository), and https://github.com/alejandrogallo/papis/issues/5 (Add zotero conversion).

**Comment by alejandrogallo** [comment]
You're right, it can be quickly fixed, alternatively you could install papis 0.6
```
pip3 install papis==0.6
```
and do it there, but I will fix it quickly and add it to the papis-zotero project

**Comment by Xunius** [comment]
I'll wait for your fix. I want to use the --link flag.

**Comment by alejandrogallo** [comment]
The importer is now working in papis-zotero, do you know how to install from master the packages ?
Or should I update versions to pypi ?

If you know how to install from source then you could do

```
papis zotero import --from-bibtex yourbib.bib --outfolder testlibrary
```
Maybe you can try it out, it will work with the master version of papis, that's why I ask you if you
can install yourself ;)

By the way, it's --from-bibtex, because there is another script that imports from the sql database.

**Comment by Xunius** [comment]
Hi,
I tried the papis-zotero importer and got partial success with it. It did read the bib file and import correctly if the entry in it has a `file` field, otherwise it would throw this line:
```
ERROR:add:run:No documents to be added
```
and that entry is not imported. I guess that's something you said you are about to address later?

Another thing I noticed is some times the new entry imported doesn't appear in `papis open` unless I run `papis --clear-cache` first. Not a bit deal though.

And lastly, once I navigate to a doc in `papis open` and hit enter, the PDF reader opens, and papis quits automatically. I don't quite remember it behaved like this before. Is it the intended? Because after I imported about 50 docs via bib file I noticed papis startup time got notably longer, about 5-7 seconds to open. It would be nice to keep papis open in such cases.

**Comment by cgxeiji** [comment]
I run into the same problem while following the bibtex importing guide from [docs](https://papis.readthedocs.io/en/latest/importing.html#importing-from-bibtex-files).

The `papis/master/examples/scripts/papis-zotero` file uses a `papis.commands.main` function from the `papis/commands/__init__.py` that seems to be deprecated. Then I realized that the import is done now from another repository: [papis/papis-zotero](https://github.com/papis/papis-zotero).

I was just wondering if the docs needs to be updated, or I am not following the guide correcly.

**Comment by dowewas2** [comment]
I am having the same issue. After updating papis, the `papis zotero` command no longer works. I tried downgrading, and I had no luck.

**Comment by teto** [comment]
I am a bit lost between the simple and sql scripts https://github.com/papis/papis/blob/master/examples/scripts/papis-zotero-sql as well as this repository https://github.com/papis/papis-zotero. Which one is the reference ? I used with success the sql one so I am tempted to close this.

**Comment by alejandrogallo** [comment]
Hi, there is a `TODO` which is to add the `zotero-sql` importer to the `papis-zotero` project.
Right now `papis zotero` can only import from a bib file, but it would be nice to be able to import from the sql also upon flag.
