### ISSUE TITLE
Error on bibtex export

### ISSUE THREAD

**Issue by supersambo** [papis/papis#950]
*papis, version 0.14

Hi, 
I am running into an issue when exporting my complete library to a bibtex file.

# how to reproduce the issue:
Command and output of `papis --log INFO export -a -f bibtex -o export.bib`:
```
Traceback (most recent call last):
  File "/home/supersambo/.local/bin/papis", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/supersambo/.local/pipx/venvs/papis/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/supersambo/.local/pipx/venvs/papis/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/supersambo/.local/pipx/venvs/papis/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/supersambo/.local/pipx/venvs/papis/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/supersambo/.local/pipx/venvs/papis/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/supersambo/.local/pipx/venvs/papis/lib/python3.12/site-packages/papis/commands/export.py", line 138, in cli
    ret_string = run(documents, to_format=fmt)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/supersambo/.local/pipx/venvs/papis/lib/python3.12/site-packages/papis/commands/export.py", line 87, in run
    .plugin(document for document in documents))
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/supersambo/.local/pipx/venvs/papis/lib/python3.12/site-packages/papis/bibtex.py", line 300, in exporter
    return "\n\n".join(to_bibtex_multiple(documents))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/supersambo/.local/pipx/venvs/papis/lib/python3.12/site-packages/papis/bibtex.py", line 540, in to_bibtex_multiple
    bib = to_bibtex(doc)
          ^^^^^^^^^^^^^^
  File "/home/supersambo/.local/pipx/venvs/papis/lib/python3.12/site-packages/papis/bibtex.py", line 627, in to_bibtex
    bib_value = author_list_to_author(document["author_list"])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/supersambo/.local/pipx/venvs/papis/lib/python3.12/site-packages/papis/bibtex.py", line 523, in author_list_to_author
    family = author.get("family")
             ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
```

I can export single entries. I understand this is due to a faulty entry in my library. Any suggestions on how I can identify the problematic entry? 

(This was still working in v0.13, I guess it was more permissive.)

**Comment by alexfikl** [comment]
Added a more helpful message in #951. Would that work?

**Comment by pmiam** [comment]
> It would be nice to have a `papis doctor` check for that too. Since it's a nested structure, `key-type` doesn't work :\

I have a prototype doctor check for this, but I was planning to improve it by also elegantly handling author "aliases" like the editor and editor_list keys. I don't have a timeline for that yet, but maybe a few weeks.

**Comment by alexfikl** [comment]
> I have a prototype doctor check for this, but I was planning to improve it by also elegantly handling author "aliases" like the editor and editor_list keys. I don't have a timeline for that yet, but maybe a few weeks.

I haven't thought about it, but think there's a chance we can just extend the `key-type` check somehow? It seems to fit in there pretty well.

**Comment by supersambo** [comment]
That works fine, thanks!
